<a href="https://colab.research.google.com/github/andresilva855/ml-lab/blob/main/Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import tensorflow as tf
import numpy as np

# **Testes utilizando Numpy**

In [ ]:
X = np.array([[10, 25], [32, 45], [12, 18]])
r, c = X.shape
print(r)
print(c)

3
2


In [ ]:
X

array([[10, 25],
       [32, 45],
       [12, 18]])

In [ ]:
X[:,0]

array([10, 32, 12])

In [ ]:
X[0,:]

array([10, 25])

# **Testes utilizando PyTorch**

In [2]:
p_X = torch.tensor([[10,25],[32,45],[12,18]])
p_X

tensor([[10, 25],
        [32, 45],
        [12, 18]])

In [6]:
p_X.shape

torch.Size([3, 2])

In [5]:
p_X[:,0]

tensor([10, 32, 12])