<a href="https://colab.research.google.com/github/andresilva855/ml-lab/blob/main/Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Preparacao**

In [43]:
import torch
import tensorflow as tf
import numpy as np

# **Testes utilizando Numpy**

In [44]:
X = np.array([[10, 25], [32, 45], [12, 18]])
r, c = X.shape
print(r)
print(c)

3
2


In [45]:
X

array([[10, 25],
       [32, 45],
       [12, 18]])

In [46]:
X[:,0]

array([10, 32, 12])

In [47]:
X[0,:]

array([10, 25])

# **Testes utilizando PyTorch**

In [48]:
p_X = torch.tensor([[10,25],[32,45],[12,18]])
p_X

tensor([[10, 25],
        [32, 45],
        [12, 18]])

In [49]:
p_X.shape

torch.Size([3, 2])

In [50]:
p_X[:,0]

tensor([10, 32, 12])

# **Testes utilizando Tensor Flow**

In [51]:
t_X = tf.Variable([[10, 25], [32, 45], [12, 18]])
t_X

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 25],
       [32, 45],
       [12, 18]], dtype=int32)>

In [52]:
t_X.shape

TensorShape([3, 2])

In [53]:
tf.shape(t_X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [54]:
t_X[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 45, 18], dtype=int32)>

# **Tranposicao**

In [55]:
X.T # NumPy example

array([[10, 32, 12],
       [25, 45, 18]])

In [56]:
p_X.T # PyTorch example

tensor([[10, 32, 12],
        [25, 45, 18]])

In [57]:
tf.transpose(t_X) # Rensor Flow example

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 32, 12],
       [25, 45, 18]], dtype=int32)>

# **Simples operacoes aritimeticas**

In [58]:
X * 2

array([[20, 50],
       [64, 90],
       [24, 36]])

In [59]:
X + 2

array([[12, 27],
       [34, 47],
       [14, 20]])

In [61]:
X * 2 + 2

array([[22, 52],
       [66, 92],
       [26, 38]])

# **Reducoes**

In [63]:
X

array([[10, 25],
       [32, 45],
       [12, 18]])

In [64]:
X.sum()

142

In [65]:
torch.sum(p_X)

tensor(142)

In [67]:
tf.reduce_sum(t_X)

<tf.Tensor: shape=(), dtype=int32, numpy=142>

In [68]:
X.sum(axis=0)

array([54, 88])

In [69]:
X.sum(axis=1)

array([35, 77, 30])

In [70]:
torch.sum(p_X, 0)

tensor([54, 88])

In [71]:
torch.sum(p_X, 1)

tensor([35, 77, 30])

In [72]:
tf.reduce_sum(t_X, 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([54, 88], dtype=int32)>

In [73]:
tf.reduce_sum(t_X, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([35, 77, 30], dtype=int32)>

# **Operacoes Dot**

In [78]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [79]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [80]:
np.dot(x, y)

12

In [89]:
x_pt = torch.tensor([25, 2, 5], dtype=torch.float16)
x_pt

tensor([25.,  2.,  5.], dtype=torch.float16)

In [92]:
y_pt = torch.tensor([0, 1, 2], dtype=torch.float16)
y_pt

tensor([0., 1., 2.], dtype=torch.float16)

In [94]:
np.dot(x_pt, y_pt)

12.0

In [93]:
torch.dot(x_pt, y_pt)

tensor(12., dtype=torch.float16)

In [95]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [96]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [98]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

# **Exercicios**

Exercicio 1

In [99]:
y = torch.tensor([[42, 4, 7, 99], [-99, -3, 17, 22]])
y

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [100]:
y.T

tensor([[ 42, -99],
        [  4,  -3],
        [  7,  17],
        [ 99,  22]])

Exercicio 2

In [101]:
x = torch.tensor([[25, 10], [-2, 1]])
x

tensor([[25, 10],
        [-2,  1]])

In [102]:
y = torch.tensor([[-1, 7], [10, 8]])
y

tensor([[-1,  7],
        [10,  8]])

In [103]:
x * y

tensor([[-25,  70],
        [-20,   8]])

Exercicio 3

In [104]:
w = torch.tensor([-1, 2, -2])
w

tensor([-1,  2, -2])

In [105]:
k = torch.tensor([5, 10, 0])
k

tensor([ 5, 10,  0])

In [106]:
torch.dot(w, k)

tensor(15)