<a href="https://colab.research.google.com/github/andresilva855/ml-lab/blob/main/Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import tensorflow as tf
import numpy as np

# **Testes utilizando Numpy**

In [37]:
X = np.array([[10, 25], [32, 45], [12, 18]])
r, c = X.shape
print(r)
print(c)

3
2


In [38]:
X

array([[10, 25],
       [32, 45],
       [12, 18]])

In [39]:
X[:,0]

array([10, 32, 12])

In [40]:
X[0,:]

array([10, 25])

# **Testes utilizando PyTorch**

In [24]:
p_X = torch.tensor([[10,25],[32,45],[12,18]])
p_X

tensor([[10, 25],
        [32, 45],
        [12, 18]])

In [25]:
p_X.shape

torch.Size([3, 2])

In [26]:
p_X[:,0]

tensor([10, 32, 12])

# **Testes utilizando Tensor Flow**

In [41]:
t_X = tf.Variable([[10, 25], [32, 45], [12, 18]])
t_X

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 25],
       [32, 45],
       [12, 18]], dtype=int32)>

In [42]:
t_X.shape

TensorShape([3, 2])

In [43]:
tf.shape(t_X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [44]:
t_X[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 45, 18], dtype=int32)>

# **Tranposicao**

In [45]:
X.T # NumPy example

array([[10, 32, 12],
       [25, 45, 18]])

In [46]:
p_X.T # PyTorch example

tensor([[10, 32, 12],
        [25, 45, 18]])

In [47]:
tf.transpose(t_X) # Rensor Flow example

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 32, 12],
       [25, 45, 18]], dtype=int32)>

# **Simples operacoes aritimeticas**

In [48]:
X * 2

array([[20, 50],
       [64, 90],
       [24, 36]])

In [49]:
X + 2

array([[12, 27],
       [34, 47],
       [14, 20]])

In [50]:
X * 2 + 2

array([[22, 52],
       [66, 92],
       [26, 38]])