<a href="https://colab.research.google.com/github/andresilva855/ml-lab/blob/main/Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import tensorflow as tf
import numpy as np

# **Testes utilizando Numpy**

In [ ]:
X = np.array([[10, 25], [32, 45], [12, 18]])
r, c = X.shape
print(r)
print(c)

3
2


In [ ]:
X

array([[10, 25],
       [32, 45],
       [12, 18]])

In [ ]:
X[:,0]

array([10, 32, 12])

In [ ]:
X[0,:]

array([10, 25])

# **Testes utilizando PyTorch**

In [ ]:
p_X = torch.tensor([[10,25],[32,45],[12,18]])
p_X

tensor([[10, 25],
        [32, 45],
        [12, 18]])

In [ ]:
p_X.shape

torch.Size([3, 2])

In [ ]:
p_X[:,0]

tensor([10, 32, 12])

# **Testes utilizando Tensor Flow**

In [11]:
t_X = tf.Variable([[10, 25], [32, 45], [12, 18]])
t_X

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 25],
       [32, 45],
       [12, 18]], dtype=int32)>

In [13]:
t_X.shape

TensorShape([3, 2])

In [12]:
t_X[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 45, 18], dtype=int32)>